; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ovulio_mini

[env:ovulio_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
board_build.partitions = partitions_4MB.csv
build_flags = 
	-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
	-DHW_VERSION=ovulio_mini
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
lib_deps = 
	xylopyrographer/LiteLED@^1.0.0
	espressif/esp32-camera @ ^2.0.0
	adafruit/Adafruit NeoPixel@^1.12.0
